import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import { SignedIn, SignedOut, UserButton, SignInButton, SignUpButton } from '@clerk/nextjs';

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
      
       
          {children}
         
        </body>
      </html>
   
  );
}